// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cXtrtCQhQ_cE6VMALmR4LcEbYNe2aRI',
    appId: '1:1064053768047:web:deb7f4facff3efa26cb29a',
    messagingSenderId: '1064053768047',
    projectId: 'habittracker-ef6d4',
    authDomain: 'habittracker-ef6d4.firebaseapp.com',
    storageBucket: 'habittracker-ef6d4.appspot.com',
    measurementId: 'G-E709XK64GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBWFJXcMnn_-iITOhY_3mM7eL1VvenXTI',
    appId: '1:1064053768047:android:5dfb8fcb74b256ee6cb29a',
    messagingSenderId: '1064053768047',
    projectId: 'habittracker-ef6d4',
    storageBucket: 'habittracker-ef6d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2vUPgbST3xWu0GzFG4Hy1hPvPbxyAUw',
    appId: '1:1064053768047:ios:f2499a174d985b6a6cb29a',
    messagingSenderId: '1064053768047',
    projectId: 'habittracker-ef6d4',
    storageBucket: 'habittracker-ef6d4.appspot.com',
    iosBundleId: 'com.example.habittrackker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2vUPgbST3xWu0GzFG4Hy1hPvPbxyAUw',
    appId: '1:1064053768047:ios:f2499a174d985b6a6cb29a',
    messagingSenderId: '1064053768047',
    projectId: 'habittracker-ef6d4',
    storageBucket: 'habittracker-ef6d4.appspot.com',
    iosBundleId: 'com.example.habittrackker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-cXtrtCQhQ_cE6VMALmR4LcEbYNe2aRI',
    appId: '1:1064053768047:web:6ceecc0b7dc5a5236cb29a',
    messagingSenderId: '1064053768047',
    projectId: 'habittracker-ef6d4',
    authDomain: 'habittracker-ef6d4.firebaseapp.com',
    storageBucket: 'habittracker-ef6d4.appspot.com',
    measurementId: 'G-5SQ8EZYRF7',
  );
}
